name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: cargo clippy --verbose

      - name: Test
        run: cargo test --verbose
